spring:
  profiles:
    active: dev

tanhua:
  sms:
    accessKey: LTAI5tBSxBRbzhXAkS8G6SmS
    secret: 4YoUATEzLrTL4nt9CdLwGoFF8GDLuF
    endpoint: dysmsapi.aliyuncs.com
    signName: 探花
    templateCode: SMS_154950909